In [22]:
from transformers import BertTokenizer, BertForTokenClassification, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

inputs = tokenizer(
    ["HuggingFace is a [CLS] company based in Paris [CLS] and New York",
    "Hello [CLS] World "], 
    add_special_tokens=False, return_tensors="pt", padding=True
)
token_ids = inputs.input_ids
print(token_ids.shape)

outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state

last_hidden_states.shape

print("mask token id", tokenizer.mask_token_id)



Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([2, 13])
mask token id 103


In [24]:
token_ids

tensor([[17662, 12172,  2003,  1037,   101,  2194,  2241,  1999,  3000,   101,
          1998,  2047,  2259],
        [ 7592,   101,  2088,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]])

In [43]:
masked_position = torch.nonzero(token_ids.squeeze() == tokenizer.cls_token_id).numpy()

masked_position

array([[0, 4],
       [0, 9],
       [1, 1]])

In [51]:
last_hidden_states = last_hidden_states[:, :, :3]
last_hidden_states

tensor([[[-0.4628, -0.1540,  0.3660],
         [-0.0718,  0.0234,  0.6171],
         [-0.4905, -0.3826,  0.3441],
         [-0.4751, -0.3955,  0.4963],
         [-0.4662, -0.1356,  0.3492],
         [-0.2884, -0.1606,  0.4776],
         [ 0.2013, -0.1857,  0.3939],
         [-0.4220, -0.1807,  0.4796],
         [-0.2899, -0.0101,  0.3269],
         [-0.4529, -0.1268,  0.3484],
         [-0.4190, -0.1185,  0.4642],
         [-0.5906, -0.0367,  0.8036],
         [-0.6655,  0.2763,  0.4465]],

        [[-0.4479,  0.2598,  0.0396],
         [-0.4392,  0.2628,  0.0397],
         [-0.2960,  0.4005,  0.2181],
         [-0.3829,  0.2139,  0.1856],
         [-0.3673,  0.2274,  0.1870],
         [-0.3872,  0.2322,  0.1599],
         [-0.3939,  0.2319,  0.1586],
         [-0.4101,  0.2441,  0.1621],
         [-0.4176,  0.2388,  0.1580],
         [-0.4097,  0.2443,  0.1633],
         [-0.4118,  0.2463,  0.1580],
         [-0.4104,  0.2449,  0.1561],
         [-0.4111,  0.2383,  0.1675]]], grad_fn=

In [15]:
masked_position = torch.nonzero(token_ids.squeeze() == tokenizer.mask_token_id)

In [101]:
indices = torch.nonzero(token_ids.flatten() == tokenizer.cls_token_id)

In [105]:
indices.flatten()

tensor([ 4,  9, 14])

In [106]:
last_hidden_states.view(-1, last_hidden_states.shape[-1]).index_select(0, indices.flatten())

tensor([[-0.4662, -0.1356,  0.3492],
        [-0.4529, -0.1268,  0.3484],
        [-0.4392,  0.2628,  0.0397]], grad_fn=<IndexSelectBackward>)

In [83]:
sentence_representations = last_hidden_states[[x.item(), y.item()] for (x,y) in masked_position]

SyntaxError: invalid syntax (817894800.py, line 1)

tensor([[[0.4295, 0.7694, 0.3053],
         [0.6503, 0.9081, 0.8211]],

        [[0.7638, 0.6187, 0.8068],
         [0.5029, 0.3763, 0.0468]],

        [[0.0187, 0.2277, 0.5768],
         [0.8983, 0.6863, 0.5825]],

        [[0.9343, 0.3692, 0.7496],
         [0.1416, 0.6753, 0.1482]]])

In [75]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [73]:
b = torch.Tensor([[0,1], [0,2], [2,3]]).int()
b

tensor([[0, 1],
        [0, 2],
        [2, 3]], dtype=torch.int32)

In [60]:
a

IndexError: index 2 is out of bounds for dimension 0 with size 2

In [ ]:
# build dataset
